export const defaultValuesMyRest = {
  name: "Name",
  country: "Country",
  state: "State",
  city: "City",
  street: "Street",
  zipCode: "12345",
  email: "email@exampple.com",
  phone: "1234567890",
  website: "http://www.example.com",
  estTimeDelivery: "30",
  price: "10",
  freeDeliveryPrice: "50",
  categories: ["italian", "chinese"],
  openTime: "8:00",
  closeTime: "21:00",
};
