enum UserActions {
  SET_IS_LOGGED = "SET_IS_LOGGED",
  SET_CURR_USER = "SET_CURR_USER",
  SET_CAN_MANAGE_ACCOUNT = "SET_CAN_MANAGE_ACCOUNT",
}

export const SET_IS_LOGGED = UserActions.SET_IS_LOGGED;
export const SET_CURR_USER = UserActions.SET_CURR_USER;
export const SET_CAN_MANAGE_ACCOUNT = UserActions.SET_CAN_MANAGE_ACCOUNT;
